<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>GeoMvdCoreWeb</groupId>
  <artifactId>GeoMvdCoreWeb</artifactId>
  <version>1.2.0</version>
  <packaging>war</packaging>
  <properties>
    <deployment.name>GeoMVDCore</deployment.name>
  </properties>
  <dependencies>
	<dependency>
	    <groupId>javax.servlet</groupId>
	    <artifactId>javax.servlet-api</artifactId>
	    <version>4.0.1</version>
	    <scope>provided</scope>
	</dependency>
    <dependency>
    	<groupId>javax</groupId>
	    <artifactId>javaee-web-api</artifactId>
	    <version>6.0</version>
	    <scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>GeoMvdCoreAPI</groupId>
		<artifactId>GeoMvdCoreAPI</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<scope>compile</scope>
	</dependency>
  </dependencies>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.2.1</version>
        <configuration>
          <warSourceDirectory>WebContent</warSourceDirectory>
          <warName>${deployment.name}-${git.commit.id}-v${git.build.version}</warName>
        </configuration>
      </plugin>
            <plugin>
          <groupId>org.wildfly.plugins</groupId>
          <artifactId>wildfly-maven-plugin</artifactId>
          <version>1.2.1.Final</version>
          <configuration>
          	<filename>${deployment.name}-${git.commit.id}-v${git.build.version}.war</filename>
          </configuration>
      </plugin>
      <plugin>
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <version>2.2.4</version>
        <executions>
            <execution>
                <id>get-the-git-infos</id>
                <goals>
                    <goal>revision</goal>
                </goals>
            </execution>
        </executions>
        <configuration>
            <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
            <prefix>git</prefix>
            <verbose>false</verbose>
            <generateGitPropertiesFile>true</generateGitPropertiesFile>
            <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
            <format>json</format>
            <gitDescribe>
                <skip>false</skip>
                <always>false</always>
                <dirty>-dirty</dirty>
            </gitDescribe>
        </configuration>
    </plugin>
    </plugins>
  </build>
</project>