
#URL GEOSERVER
URLgeoserver=http://geoserver:8080/geoserver
URLcore=http://wildfly:8080/geomvd-app/api/core/

#datasources conexion DB
pluginetaDS=jboss/datasources/pluginetaDS

#tipo de medición: lineal = false - geodésica = true
geodesicMeasure=true

#url Manual
URLmanual=https://s1.q4cdn.com/806093406/files/doc_downloads/test.pdf
