# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IMLayerLoader
                                 A QGIS plugin
 Plugin para cargar y gestionar capas geoespaciales desde GeoServer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-23
        copyright            : (C) 2022 by -
        email                : -
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IMLayerLoader class from file IMLayerLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IM_layer_loader import IMLayerLoader
    return IMLayerLoader(iface)
