# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IMLayerLoader
                                 A QGIS plugin
 Plugin para cargar y gestionar capas geoespaciales desde GeoServer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-11-23
        git sha              : $Format:%H$
        copyright            : (C) 2022 by -
        email                : -
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import shutil

from PyQt5.QtCore import Qt, QTimer
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QLineEdit, QCheckBox, QListWidget, QToolButton
from qgis.PyQt import QtWidgets
from qgis.core import QgsLogger, QgsMessageLog, Qgis, QgsProject, QgsExpression, QgsFeatureRequest
from qgis.utils import iface

from .modulos.formularios.atributosFormulario import AtributosFormularios
from .modulos.formularios.codigueras import Codigueras
from .modulos.seguridad.funcionesAutenticacion import FuncionesAutenticacion
from .modulos.utilidades.funcionesExportacion import FuncionesExportacion
from .modulos.aplicaciones.aplicaciones import Aplicaciones
from .modulos.servicios.geoserverApi import GeoserverApi
from .modulos.properties.configProperties import ConfigProperties
from .modulos.utilidades.funcionesMapa import FuncionesMapa
from .modulos.configuraCapasProyecto import ConfiguraCapasProyecto
from .modulos.cargaCapasProyecto import CargaCapasProyecto
from .modulos.utilidades.logger import SafePluginLogger
from PyQt5.QtWidgets import QProgressDialog, QLabel

from qgis.core import QgsMessageLog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .IM_layer_loader_dialog import IMLayerLoaderDialog
import os.path
import re

from PyQt5.QtWidgets import QWidget, QVBoxLayout, QPushButton, QFileDialog
from qgis.core import QgsProject
from qgis.core import QgsApplication

# Inicialización segura
try:
    logger = SafePluginLogger.init_logger()
    logger.info("Plugin inicializado correctamente")
except Exception as e:
    print(f"Error inicializando logger: {str(e)}")
    logger = logger.getLogger("dummy_logger")

class IMLayerLoader:
    """QGIS Plugin Implementation."""

    erroresEnCodigueras = []

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IMLayerLoader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IM carga de capas')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.original_message_handler = None  # Para almacenar el manejador por defecto

        # Capas base efectivas para el/los workspace(s) seleccionados actualmente en listApp
        # (seccion, capa, nombre) - ver ConfigProperties.getCapasBaseParaWorkspaces
        self._capaBaseEntradas = []


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IMLayerLoader', message)


    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        icon_path = ':/plugins/IM_layer_loader/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'&IM configura capas'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        Aplicaciones.agregarBusquedaUbicaciones()
        Aplicaciones.agregarExportarLogs()

        #QgsApplication.messageLog().messageReceived.connect(self.log_message)

        # 1. Desconectar cualquier manejador existente
        self.original_message_handler = QgsApplication.messageLog().messageReceived

        try:
            QgsApplication.messageLog().messageReceived.disconnect()
        except Exception as e:
            logger.warning(f"No se pudo desconectar manejador de mensajes: {str(e)}")

        # 2. Conectar nuestro manejador seguro
        try:
            QgsApplication.messageLog().messageReceived.connect(self.safe_log_message)
        except Exception as e:
            logger.error(f"Error conectando safe_log_message: {str(e)}")


    def safe_log_message(self, message, tag, level):

        """
        Manejador principal que:
        - Filtra contraseñas
        - Evita recursión
        - Procesa logs a archivo
        """
        try:
            # 1. Desconectar temporalmente para evitar recursión
            QgsApplication.messageLog().messageReceived.disconnect(self.safe_log_message)

            # 2. Sanitizar y mostrar el mensaje en QGIS
            clean_msg = self.sanitize_log_message(message)
            QgsMessageLog.logMessage(clean_msg, tag, level)

            # 3. Procesar para archivo de log (solo WFS/WMS)
            if tag in ["WFS", "WMS"] and level in [1, 2]:  # 1=WARNING, 2=ERROR
                self.process_log_message(message, tag, level)

        finally:
            # 4. Reconectar el manejador al finalizar
            QgsApplication.messageLog().messageReceived.connect(self.safe_log_message)

    def unload(self):

        QgsApplication.messageLog().messageReceived.disconnect(self.safe_log_message)
        if self.original_message_handler:
            QgsApplication.messageLog().messageReceived.connect(self.original_message_handler)

        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IM carga de capas'),
                action)
            self.iface.removeToolBarIcon(action)

        SafePluginLogger.shutdown_logger()

        #QgsApplication.messageLog().messageReceived.disconnect(self.log_message)


    def sanitize_log_message(self, message):
        """Elimina user/password de manera eficiente."""
        if not any(k in message for k in ["password="]):
            return message
        return re.sub(r"(password)='[^']*'", "", message).strip()

    def process_log_message(self, message, tag, level):
        """Lógica específica para logging a archivo."""
        clean_msg = self.sanitize_log_message(message)

        if level == 1:  # WARNING
            if "Probablemente es un esquema" in message:
                logger.error(f"Geoserver - {tag}: {clean_msg}")
                self.show_layer_error(message)
            else:
                logger.warning(f"{tag}: {clean_msg}")
        else:  # ERROR (level == 2)
            logger.error(f"{tag}: {clean_msg}")

    def show_layer_error(self, message):
        """Muestra MessageBox para errores de capa."""
        typename = re.search(r"typename='([^']*)'", message)
        QtWidgets.QMessageBox.warning(
            None,
            "Error en capa",
            f"No se pudo cargar: {typename.group(1) if typename else 'capa desconocida'}\n"
            "Verifique en Geoserver."
        )

    def traerWorkspaces(self):
        retorno=""
        urlGeoserver = ConfigProperties.getPropery("Geoserver", "urlApi")
        listApp = self.dlg.findChild(QListWidget, "listApp")
        self.userLogin = self.dlg.findChild(QLineEdit, "lineEditUser").text()
        self.passLogin = self.dlg.findChild(QLineEdit, "lineEditPass").text()

        if self.userLogin == "" or self.passLogin == "":
            retorno = "Debe ingresar Usuario y Contraseña."
        else:
            #INVOCO LA API DE GEOSERVER PARA TRAERME LOS WORKSPACES DEL USUARIO
            workspaces = GeoserverApi.getWorkspacesUser(urlGeoserver, self.userLogin, self.passLogin)
            cantidadWorkspaces = 0
            if workspaces is not None:
                vieneMetadataWorkspace = False
                try:
                    cantidadWorkspaces = len(workspaces['workspaces']['workspace'])
                    if cantidadWorkspaces > 0:
                        vieneMetadataWorkspace = True
                except:
                    vieneMetadataWorkspace = False
                if vieneMetadataWorkspace:
                    for wksp in workspaces['workspaces']['workspace']:
                        listApp.addItem(wksp['name'].upper())
                    self.dlg.findChild(QLineEdit, "lineEditUser").setEnabled(False)
                    self.dlg.findChild(QLineEdit, "lineEditPass").setEnabled(False)
                    self.dlg.findChild(QToolButton, "authUser").setVisible(False)
                    self.dlg.findChild(QToolButton, "authUserAgain").setVisible(True)
                    if cantidadWorkspaces == 1:
                        listApp.setCurrentRow(0)
                        listApp.item(0).setSelected(True)
                else:
                    retorno = "No se pudo recuperar ningun workspace"
            else:
                retorno = "No se pudo recuperar ningun workspace"
        if retorno != "":
            QtWidgets.QMessageBox.information(None, "Proceso Carga y Configuración Capas", retorno)

    # Slots fijos del dialogo (.ui) reusados como "casilleros" genericos de capa base - la
    # cantidad/etiqueta/URL real sale de ConfigProperties.getCapasBaseParaWorkspaces, no de aca.
    CAPA_BASE_CHECKBOXES = ["cbox_IM", "cbox_OSM", "cbox_IDE", "cbox_capaBase4"]

    def actualizarCapasBaseUI(self):
        """Las capas base disponibles dependen del/los workspace(s) que esten seleccionados en
        listApp (workspace-demo: cartografia de Montevideo; workspace-demo-4326: IDEuy + OSM +
        Google, estas dos ultimas disponibles pero no tildadas por defecto) - ver
        ConfigProperties.getSeccionCapasBase/getCapasBaseParaWorkspaces. Se llama cada vez que
        cambia la seleccion de workspaces."""
        listApp = self.dlg.findChild(QListWidget, "listApp")
        workspaces = [item.text().lower() for item in listApp.selectedItems()]
        self._capaBaseEntradas = ConfigProperties.getCapasBaseParaWorkspaces(workspaces)
        for i, cboxName in enumerate(self.CAPA_BASE_CHECKBOXES):
            cbox = self.dlg.findChild(QCheckBox, cboxName)
            if i < len(self._capaBaseEntradas):
                _, _, nombre, porDefecto = self._capaBaseEntradas[i]
                cbox.setText(nombre)
                cbox.setChecked(porDefecto)
                cbox.setVisible(True)
            else:
                cbox.setChecked(False)
                cbox.setVisible(False)

    def habilitaAutenticar(self):
        self.dlg.findChild(QLineEdit, "lineEditUser").setText("")
        self.dlg.findChild(QLineEdit, "lineEditPass").setText("")
        self.dlg.findChild(QListWidget, "listApp").clear()
        self.dlg.findChild(QToolButton, "authUserAgain").setVisible(False)
        self.dlg.findChild(QLineEdit, "lineEditUser").setEnabled(True)
        self.dlg.findChild(QLineEdit, "lineEditPass").setEnabled(True)
        self.dlg.findChild(QToolButton, "authUser").setVisible(True)
        self.dlg.findChild(QLineEdit, "lineEditUser").setFocus()

    def run(self):

        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IMLayerLoaderDialog()
            authUser = self.dlg.findChild(QToolButton, "authUser")
            authUser.clicked.connect(self.traerWorkspaces)
            authUserAgain = self.dlg.findChild(QToolButton, "authUserAgain")
            authUserAgain.clicked.connect(self.habilitaAutenticar)
            self.dlg.findChild(QListWidget, "listApp").itemSelectionChanged.connect(self.actualizarCapasBaseUI)

        retorno = ""
        self.erroresEnCodigueras.clear()
        #ruta_archivo_logs = FuncionesExportacion.obtenerPathArchivoLogs()
        #logging.basicConfig(filename=ruta_archivo_logs, level=logging.INFO, filemode='w', format='%(asctime)s - %(levelname)s: %(message)s')

        l_ambiente = self.dlg.findChild(QLabel, "Ambiente")
        l_ambiente.hide()
        if ConfigProperties.getPropery("Ambiente", "avisoTest") == "S":
            l_ambiente.show()
            ambiente = "test"
        else:
            ambiente = "produccion"

        l_nroVersion = self.dlg.findChild(QLabel, "NroVersion")
        l_nroVersion.setText("Versión: " + ConfigProperties.getVersion())
        l_nroVersion.setStyleSheet("color: black; font-weight: bold;")
        l_nroVersion.setAlignment(Qt.AlignRight)

        listApp = self.dlg.findChild(QListWidget, "listApp")
        listApp.clear()

        l_userLogin = self.dlg.findChild(QLineEdit, "lineEditUser")
        l_userLogin.setText("")
        l_userLogin.setFocus()
        l_passLogin = self.dlg.findChild(QLineEdit, "lineEditPass")
        l_passLogin.setEchoMode(QLineEdit.Password)
        l_passLogin.setText("")

        # Las capas base dependen del workspace seleccionado - se resuelven recien cuando hay
        # seleccion real en listApp (ver actualizarCapasBaseUI, conectado a itemSelectionChanged).
        self.actualizarCapasBaseUI()

        cbox_recargaCapas = self.dlg.findChild(QCheckBox, "cbox_recargar")
        cbox_recargaCapas.setChecked(True)

        self.dlg.findChild(QLineEdit, "lineEditUser").setEnabled(True)
        self.dlg.findChild(QLineEdit, "lineEditPass").setEnabled(True)
        self.dlg.findChild(QToolButton, "authUser").setVisible(True)
        self.dlg.findChild(QToolButton, "authUserAgain").setVisible(False)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Create the progress dialog
            progress_dialog = QProgressDialog("Cargando...", None, 0, 0, self.iface.mainWindow())
            progress_dialog.setWindowTitle("Cargando...")
            progress_dialog.setRange(0, 0)
            progress_dialog.show()

            self.userLogin = l_userLogin.text()
            self.passLogin = l_passLogin.text()
            logger.info("             ------")
            logger.info(f"<<< Pantalla Principal - Usuario: {self.userLogin} - Version: {ConfigProperties.getVersion()} - ambiente: {ambiente} >>>")

            workSpacesSelected = listApp.selectedItems()

            #EXIGIMOS QUE VENGA UNA APLICACION VALIDA:
            if len(workSpacesSelected) < 1:
                retorno = "Debe seleccionar una Aplicación válida."
            #EXIGIMOS QUE VENGA UN USUARIO Y PASSWORD:
            elif self.userLogin == "" or self.passLogin == "":
                retorno = "Debe ingresar Usuario y Contraseña."
            else:
                # cargaCapaBaseDict: capa -> (seccion, seCarga) - ver ConfigProperties.getCapasBaseParaWorkspaces
                cargaCapaBaseDict = {}
                for i, (seccion, capa, nombre, porDefecto) in enumerate(self._capaBaseEntradas):
                    cbox = self.dlg.findChild(QCheckBox, self.CAPA_BASE_CHECKBOXES[i])
                    cargaCapaBaseDict[capa] = (seccion, cbox.isChecked())

                sobreEscribirCapas = cbox_recargaCapas.isChecked()

                #CARGAMOS LAS CAPAS QUE EL WORKSPACE TENGA HABILITADAS:
                retorno = CargaCapasProyecto.cargaCapasProyecto(workSpacesSelected, self.userLogin, self.passLogin, cargaCapaBaseDict, sobreEscribirCapas)

                #CARGAMOS Y DISPONIBILIZAMOS EN QGIS LAS FUNCIONES QUE SE NECESITAN PARA EXPRESIONES Y CAMPOS CALCULADOS
                Aplicaciones.disponibilizarFuncionesParaExpresiones()
                
                #VAMOS A INVOCAR LA CONFIGURACION PARA TODAS LAS CAPAS DEL PROYECTO:
                retorno += ConfiguraCapasProyecto.configuraCapasProyecto(self.userLogin).strip()

                ###################  RECARGAR CODIGUERAS FALLIDAS ####################
                for nombreUsuario, nombreCapa, nombreAtributo, capaCodiguera, codigueras, aplicacion in self.erroresEnCodigueras:
                    print(f'Iterando cargar codiguera: {nombreUsuario}, {nombreCapa}, {nombreAtributo}, {capaCodiguera}, {aplicacion}')
                    logger.info(f'Reintentando cargar codiguera: {nombreUsuario}, {nombreCapa}, {nombreAtributo}, {capaCodiguera}, {aplicacion}')
                    valoresCodiguera = Codigueras.procesarDatosCapaCodiguera(nombreUsuario, capaCodiguera, aplicacion, codigueras)
                    if valoresCodiguera is not None:
                        AtributosFormularios.cargaCodigueraAtributo((aplicacion+":"+nombreCapa), nombreAtributo, valoresCodiguera)
                        QtWidgets.QMessageBox.information(None, "Configuración de capas", f'Se pudo configurar {nombreCapa}:{capaCodiguera} con éxito')
                        logger.info(f'Reintento OK de carga codiguera: {capaCodiguera}- de capa {nombreCapa} y atributo {nombreAtributo}. {aplicacion} - {nombreUsuario}')
                    else:
                        logger.error(f'Error Reintento carga codiguera: {capaCodiguera} de capa {nombreCapa} y atributo {nombreAtributo}. {aplicacion} - {nombreUsuario}')
                        print(f'Error en re carga/conf de codiguera. nombreCapa: {nombreCapa}. capaCodiguera: {capaCodiguera}. nombreAtributo:{nombreAtributo}')
                        QtWidgets.QMessageBox.information(None, "Configuración de capas", f'Reintento: No se pudo configurar la capa {nombreCapa} con los datos de {capaCodiguera} correctamente', QtWidgets.QMessageBox.Ok)


                self.erroresEnCodigueras.clear()


            for  item in workSpacesSelected:
                logger.info("Workspace seleccionado: " + item.text().upper())
                workspace = item.text().lower()
                if(Aplicaciones.existeCapaCargadaEnWorkspace(workspace)):
                    Aplicaciones.completarConfigAplicaciones(workspace)
                else:
                    print("No existen capas para " + workspace)

            if retorno == "":
                retorno = "Se Configuraron Las Capas Correctamente"
                logger.info("Se Configuraron Las Capas Correctamente")


            QtWidgets.QMessageBox.information(None, "Proceso Carga y Configuración Capas", retorno)
            progress_dialog.close()
            FuncionesMapa.refrescarZoomCapasCanvas()

