[ServicioRest]
urlCapas=http://localhost:8080/geoserver/rest/plugineta/public/replaceAppName/layers/
urlubicacionesRestWEB=https://api.montevideo.gub.uy/ubicacionesRest/

[Geoserver]
urlComplementoWFS=/wfs?service=WFS&version=auto&request=GetFeature&restrictToRequestBBOX=1&format=application/json
urlApi=http://localhost:8080/geoserver

[CapasBase]
nombreCapaIde=Fotos IDE
urlCapaIde=contextualWMSLegend=0&crs=EPSG:32721&dpiMode=7&featureCount=10&format=image/png&layers=im-fotos:fotos_2024&styles&tileMatrixSet=im-fotos:fotos_2024-wmsc-8&tilePixelRatio=0&url=https://montevideo.gub.uy/app/geowebcache/capabilities/im-fotos_fotos_2024.xml

nombreCapaOSM=OpenStreetMap
urlCapaOSM=crs=EPSG:32721&format=image/png&type=xyz&url=http://tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0

nombreCapaBaseIM=Carto Basica IM
urlCapaBaseIM=crs=EPSG:32721&dpiMode=7&featureCount=10&format=image/png&layers=mapstore-base:capas_base&styles&tileMatrixSet=mapstore-base:capas_base-wmsc-8&tilePixelRatio=0&url=https://montevideo.gub.uy/app/geowebcache/capabilities/mapstore-base_capas_base.xml

[Ambiente]
avisoTest=S
