[ServicioRest]
urlCapas=https://gis.imm.gub.uy/api/plugineta/rest/public/replaceAppName/layers/
urlubicacionesRestWEB=https://api.montevideo.gub.uy/ubicacionesRest/

[Geoserver]
urlComplementoWFS=/wfs?service=WFS&version=auto&request=GetFeature&restrictToRequestBBOX=1&srsname=EPSG:32721&format=application/json
urlApi=https://geoserver-ed.imm.gub.uy/geoserver

[CapasBase]
nombreCapaIde=Fotos IDE
urlCapaIde=contextualWMSLegend=0&crs=EPSG:32721&dpiMode=7&featureCount=10&format=image/png&layers=ORTOFOTOS_2019&styles&url=https://mapas.ide.uy/geoservicios/WMS/WMS_Uruguay_IDEuy_Ortofotos

nombreCapaOSM=OpenStreetMap
urlCapaOSM=crs=EPSG:32721&format=image/png&type=xyz&url=http://tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0

nombreCapaBaseIM=Carto Basica IM
urlCapaBaseIM=crs=EPSG:32721&dpiMode=7&format=image/png&layers=sur_carto_basica&styles=&url=https://geoserver-ssl.imm.gub.uy/geoserver/wms

[Ambiente]
avisoTest=N

[Imnube]
urlBaseImnube=https://imnube.imm.gub.uy/alfresco/api/-default-/public/alfresco/versions/1
idNodeCarpeta=cca24b6e-c7c3-4b77-bd17-72645a1f329a
urlBasePublico=https://imnube.montevideo.gub.uy/share/s
