[ServicioRest]
#urlCapas=http://10.213.3.43:8080/api/plugineta/rest/public/replaceAppName/layers/
urlCapas=https://desa-gis.imm.gub.uy/api/plugineta/rest/public/replaceAppName/layers/
urlubicacionesRestWEB=https://api.montevideo.gub.uy/ubicacionesRest/

[Geoserver]
urlComplementoWFS=/wfs?service=WFS&version=auto&request=GetFeature&restrictToRequestBBOX=1&srsname=EPSG:32721&format=application/json
#urlApi=https://desa-geoserver-ed.imm.gub.uy/geoserver
urlApi=https://desa-geoserver-ed.imm.gub.uy/geoserver

[CapasBase]
nombreCapaIde=Fotos IDE
urlCapaIde=contextualWMSLegend=0&crs=EPSG:32721&dpiMode=7&featureCount=10&format=image/png&layers=ORTOFOTOS_2019&styles&url=https://mapas.ide.uy/geoservicios/WMS/WMS_Uruguay_IDEuy_Ortofotos

nombreCapaOSM=OpenStreetMap
urlCapaOSM=crs=EPSG:32721&format=image/png&type=xyz&url=http://tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0

nombreCapaBaseIM=Carto Basica IM
urlCapaBaseIM=crs=EPSG:32721&dpiMode=7&format=image/png&layers=sur_carto_basica&styles=&url=https://geoserver-ssl.imm.gub.uy/geoserver/wms

[Ambiente]
avisoTest=S

[Imnube]
urlBaseImnube=https://nube-preprod.imm.gub.uy/alfresco/api/-default-/public/alfresco/versions/1
idNodeCarpeta=093efbeb-20c9-4105-9072-74eb5f075f09
urlBasePublico=https://nube-preprod.imm.gub.uy/#/preview/s
usr=im9000002
pass=im9000002
