#Direccion donde se encuentra los xml 
dirAPP=

#URL GEOSERVER
URLgeoserver=https://geoserver-ssl.imm.gub.uy/geoserver
URLcore=https://intranet.imm.gub.uy/api/geomvd/core/
URLgeoserverProxy=https://intranet.imm.gub.uy/app/geomvd/geoserverproxy

#caracteresProhibidos=["'",":", "*", "?", "<", ">", "|", "/", "\", "tabulador horizontal", "salto de linea"]
#caracteres especiales para remplazar deben ir en codigo ASCII y separados por coma ,
CARACTERES_REPLACE=39,58,42,63,60,62,124,47,92,9,10
SECUENCIA_USA_PK=secuencia_usa_pk