
#URL GEOSERVER
URLgeoserver=http://localhost:8080/geoserver
URLcore=http://localhost:8082/api/plugineta/core/
URLgeoserverProxy=http://localhost:8082/geoserverproxy

#URL Servicios Rest
URLrestserver=https://api.montevideo.gub.uy/ubicacionesRest/

#datasources conexion DB
brfDS=jboss/datasources/brfDS
stmDS=jboss/datasources/stmDS
nucleoDS=jboss/datasources/nucleoDS
brhDS=jboss/datasources/brhDS
citimDS=jboss/datasources/citimDS

REPORTS_BASE_URL=http://localhost:8082/reports/
REPORTS_PATH=

#tipo de medicion: lineal = false - geodesica = true
geodesicMeasure=true

#url Manual
URLmanual=

rolaplicacion=GIS_ADMINS;GIS_EDITORS
