
#URL GEOSERVER
URLgeoserver=https://desa-geoserver.imm.gub.uy/geoserver
URLcore=https://desa-intranet.imm.gub.uy/api/geomvd/core/
URLgeoserverProxy=https://desa-intranet.imm.gub.uy/app/dfr/geoserverproxy

#URL Servicios Rest
URLrestserver=http://desa.imm.gub.uy:8080/ubicacionesRestWEB

#datasources conexion DB
brfDS=jboss/datasources/brfDS
stmDS=jboss/datasources/stmDS
nucleoDS=jboss/datasources/nucleoDS
brhDS=jboss/datasources/brhDS
citimDS=jboss/datasources/citimDS

REPORTS_BASE_URL=https://desa-intranet.imm.gub.uy/app/dfr/reports/
REPORTS_PATH=

#tipo de medición: lineal = false - geodésica = true
geodesicMeasure=true

#url Manual 
URLmanual=https://s1.q4cdn.com/806093406/files/doc_downloads/test.pdf

rolaplicacion=RA_GEOSDFR_EDICION;RA_GEOSDFR_SELECTIVA_EDICION
